export enum QueryValidity {
  VALID_QUERY,
  INVALID_QUERY,
  QUERY_VALIDITY_ERROR
}

export enum QueryTruthfulness {
  TRUE_QUERY,
  FALSE_QUERY,
  QUERY_TRUTHFULNESS_ERROR
}

export enum QueryState {
  READY_TO_RECEIVE,
  LOADING_VALIDITY_CHECKING,
  LOADING_SOURCES_SEARCHING,
  LOADING_FACT_CHECKING,
  QUERY_COMPLETE
}